### ISSUE TITLE
"fontsize" for legend labels doesn't work with showfig()

### ISSUE THREAD

**Issue by melodyjulia** [GenericMappingTools/GMT.jl#1157]
"fontsize" doesn't work in the following code snippet:
`lines(1:12, 1:12, legend=(label="data",pos=:LT,box=:none,fontsize=6))`
`showfig()`

But "fontsize" works in the following way:
`lines(1:12, 1:12, legend=(label="data",pos=:LT,box=:none,fontsize=6),show=true)
`

Tested with GMT.jl v0.44.8 under Linux.

**Comment by joa-quim** [comment]
Hmm, this is a much more complicated case than I first thought. It's not only ``fontsize`` but I believe all non-default settings in legend that are lost when we don't call the ``show`` option. When we call ``showfig()`` that info was already lost. In theory it should be possible to find the relevant bits and save them somewhere so that ``showfig()`` could retrieve it, but not a straightforward operation.

**Comment by joa-quim** [comment]
But maybe this is solved in latest master. I mean this case now works, just hope that solution does not backfire somewhere.

**Comment by melodyjulia** [comment]
yes, it works now. Thanks!
