### ISSUE TITLE
Installation failure in MacOs

### ISSUE THREAD

**Issue by lazarusA** [GenericMappingTools/GMT.jl#462]
I'm running Julia 1.5.1 where I do have GMT.jl installed, but when I called it it says... 
```
> using GMT
> You don't seem to have GMT installed and I don't currently install it automatically,
> so you will have to do it yourself. Please follow instructions bellow.
> https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md
```

But, I do have GMT installed in the following location: 

> /Applications/GMT-6.1.1.app/Contents/MacOS/GMT-6.1.1

what should I do to get it properly working? Thanks.

**Comment by joa-quim** [comment]
Did you install the GMT bundle? If yes, I'm sorry but it won't work. Not for the reason you encountered but because MacOS manages to screw a lot of paths to dependencies and you'd find dependency conflicts (zlib for example). The solution is to build GMT using Homebrew (the GMT page has [instructions ](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md#install-via-homebrew) for that).

But still about the error you found, the issue is that GMT is not in your path, so when ``GMT.jl`` tries to run this
```
julia> run(`gmt --version`)
```
it doesn't find it.

**Comment by lazarusA** [comment]
Oh, I see. Ok. Doing the following steps works just fine. 
First 
```
$ brew install gmt
$ brew install ghostscript graphicsmagick ffmpeg
```
and then in the julia repl
```
> ] add GMT
> using GMT
```
is ok.
