### ISSUE TITLE
GMTver is not in string type

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/GMT.jl#476]
Tried GMT.jl in the [try-gmt](https://github.com/GenericMappingTools/try-gmt) environment. The `GMTver` variable is in `float64` type and it reports `6.109999999999999` instead of `6.1.1`.

![image](https://user-images.githubusercontent.com/3974108/99155731-8f81fa80-2688-11eb-95ef-302ef909632c.png)

One more question: how to show the installed GMT.jl version in a Julia console?

**Comment by joa-quim** [comment]
Yes, ``GMTver`` is a float variable because I need to do several internal decisions depending on the GMT version installed and a float is much more handy that a string. It prints that ugly number because 0.1 has no exact representation in binary. It will look nicer with GMT 6.2. But that variable is for internal use so no big deal with that floating point feature.

To get the GMT.jl version one can do

```
 julia> using Pkg

julia> Pkg.status("GMT")
Status `C:\Users\joaqu\.julia\environments\tomls\Project.toml`
  [5752ebe1] GMT v0.27.0 `C:\Users\joaqu\.julia\dev\GMT`
```

**Comment by seisman** [comment]
> To get the GMT.jl version one can do
> 
> ```
>  julia> using Pkg
> 
> julia> Pkg.status("GMT")
> Status `C:\Users\joaqu\.julia\environments\tomls\Project.toml`
>   [5752ebe1] GMT v0.27.0 `C:\Users\joaqu\.julia\dev\GMT`
> ```

Thanks. Is there a good way to check the GMT version in a Julia console if `GMTver` is only for internal use?

**Comment by joa-quim** [comment]
Well, ``GMTver`` is obtained by parsing the output of
```
julia> readlines(`gmt --version`)[1][1:5]
"6.2.0"
```

**Comment by seisman** [comment]
Looks like an ugly way to display the GMT version. Closing.
