### ISSUE TITLE
GMT is not getting right bin directory for gmt

### ISSUE THREAD

**Issue by bulbulahmmed** [GenericMappingTools/GMT.jl#579]
ERROR: LoadError: InitError: could not load library "/usr/local/Cellar/gmt/6.1.1_1/lib/libgmt.dylib"
dlopen(/usr/local/Cellar/gmt/6.1.1_1/lib/libgmt.dylib, 1): image not found

I updated gmt from 6.1.1_1 to 6.1.1_5. My current bin dir is /usr/local/bin/gmt. Now, I am getting this error.

**Comment by joa-quim** [comment]
Hi,

No idea what is that 6.1.1_5 version. GMT have not changed (yet) since 6.1.1 and we may thank Homebrew for keep changing the names all the time. So convenient.

Please try this. It will be the first time this solution is attempted but I'm expecting it to work. In Julia REPL type this
```
touch(pathof(GMT))
```
then restart Julia. It should work again (after a pre-compiling step)

**Comment by bulbulahmmed** [comment]
Hi Joa-quim, 

Thanks for your reply. Your command is not working on my Julia REPL. 

Best,
Bulbul

**Comment by bulbulahmmed** [comment]
Your this comment worked that I got from a different issue:
Anyway try to delete your equivalent of mine C:\Users\joaqu\.julia\compiled\v1.6\GMT and launch Julia again. This will force a precompile.

**Comment by joa-quim** [comment]
It helps, for future cases, explaining what *is not working on my Julia REPL.*. What was the error?
Does this instead forces a precompilation?
```
run(`touch $(pathof(GMT))`)
```
