### ISSUE TITLE
Time series data shifted

### ISSUE THREAD

**Issue by jmkuhn** [GenericMappingTools/GMT.jl#674]
I am trying to plot a short time series (a few seconds).  With my initial plot, the axis seemed correct but no data was plotted.  When I greatly increased the range on the x axis, my data is plotted but shifted by 1 day.

GMT.jl v0.35.0
GMT 6.2.0

```
using Dates, GMT

starttime = DateTime(2021, 2, 3, 4, 5, 0)
endtime = starttime + Second(4)
x = collect(starttime:Second(1):endtime)
y = collect(0.0:4.0)
plot(x, y, region=(starttime, endtime, 0, 4), lw=:thick, savefig="short_time.png", show=true)
plot(x, y, region=(starttime, endtime + Day(5), 0, 4), lw=:thick, savefig="long_time.png", show=true)
```
![short_time](https://user-images.githubusercontent.com/8557421/128199370-766ee858-33a8-4bcc-9621-bd8a010814cb.png)
![long_time](https://user-images.githubusercontent.com/8557421/128199414-ebf057cb-3a86-4f6d-a956-a8efa05a02e3.png)

**Comment by jmkuhn** [comment]
Should TIME_SYSTEM be RATA instead of RD0001?

https://github.com/GenericMappingTools/GMT.jl/blob/c6bc7031cf668db2507be206158c04c3ec8074d3/src/common_options.jl#L2911-L2915

```
julia> Dates.value(DateTime(0, 12, 31))
0
```

**Comment by joa-quim** [comment]
Thanks for looking into this. I'll try to look at it but these summer days with visitors don't leave me much time. I remember to had to pick RD0001 to make [this example](https://www.generic-mapping-tools.org/GMT.jl/dev/gallery/isc.jl.html) but otherwise plotting time series is indeed something that lacks more testing.
