### ISSUE TITLE
Problem labelling equal size colorbar

### ISSUE THREAD

**Issue by amarux** [GenericMappingTools/GMT.jl#896]
Hi!

I am having problems trying to label a discrete equal size color bar. 
For example, I am using: 

```
cpt_test  = makecpt(cmap=(:forestgreen,:darkseagreen3,:darkorange1,:red3,:steelblue4), range=(1,6,1),  no_bg=true)
cpt_test.label = ["Good", "Probgood", "Probbad", "bad", "changed"]
colorbar(pos=(paper=true, anchor="2.5i/1i", justify=:CM, size=(1.7,0.22)), axes=:none,  equal=(gap=0.1), cmap=cpt_test, show=1)
```
With this code I got a color bar labelled with the "lower boundary z-value for the annotation", as indicated in the documentation
However, I am wondering if in GMT.jl I could get something like the image below

![image](https://user-images.githubusercontent.com/8120615/169421080-66e7ffd1-e436-46e7-acce-5d0bee595afd.png)

Thank you!

**Comment by joa-quim** [comment]
Hi @amarux, 

Well I think you found a bug in GMT. More specifically in the internal machinery that communicates with external interfaces like is the case with Julia. The problem seems to be that the labels are ignored.
But you can make it work with a trick. Save the colormap into a disk file, open it in an editor and add the labels at the end of each line. 
```
gmtwrite("test.cpt", test_cpt)
```
then, after the edition the contents look like this
```
1	forestgreen	2	forestgreen	;Good
2	darkseagreen3	3	darkseagreen3	;Probgood
3	darkorange1	4	darkorange1	;Probbad
4	red3	5	red3	;bad
5	steelblue4	6	steelblue4	;changed
B	black
F	white
N	128
``` 

next this works (you we mixing inches and cm. Life is simpler in cm).
```
colorbar(pos=(paper=true, anchor="2.5i/1i", justify=:CM, size=("1.7i","0.22i")), axes=:none,  equal=(gap=0.1), cmap="test.cpt", show=1)
```

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/169538723-850d3ec7-5293-418e-94ce-79c691f365ed.png)

**Comment by joa-quim** [comment]
Hmm, it actually works if we do as said in the manual (the ``makecpt`` GMT man) and put the labels in the **T** or **range** option.
```
test_cpt  = makecpt(cmap=(:forestgreen,:darkseagreen3,:darkorange1,:red3,:steelblue4), no_bg=true, range="Good,Probgood,Probbad,bad,changed");
```

**Comment by amarux** [comment]
Nice! Thank you again!
